#' GE_scoreeq_sim_vec.R
#'
#' VECTORIZED VERSION
#'
#' Here we perform simulation to verify that we have solved for
#' the correct alpha values. 
#' No vector covariates yet, just scalars.
#' Assume all covariates are marginally normal and jointly multivariate normal,
#' with the exception of G, which is generated by thresholding two (pairwise independent) normals.
#' Assume all covariates have variance 1, except for G.
#  Assume all fitted covariates are centered at 0.
#' Assume F=E^2 and W=M^2.
#' 
#' @param beta_list A vector of the effect sizes in the true model.
#' Use the order beta_0, beta_G, beta_E, beta_I, beta_Z, beta_M.
#' If Z or M is a vector, then beta_Z and beta_M should be vectors and
#' beta_list should be a LIST! If it is not a list, then Z and M will be treated as scalars.
#' @param rho_list A vector of the 6 pairwise covariances between the
#' covariates.  These should be in the order (1) cov_GE (2) cov_GZ (3) cov_EZ
#' (4) cov_GW (5) cov_EW (6) cov_ZW.
#' Again if Z or M are vectors then terms like cov_GZ should be vectors (in the appropriate order)
#' and rho_list should be a LIST!
#' If Z or M are vectors, then cov_ZW should be a vector in the order (cov(Z_1,W_1),...,cov(Z_1,W_q),
#' cov(Z_2,W_1),........,cov(Z_p,W_q) where Z is a vector of length p and W is a vector of length q.
#' @param cov_Z Only used if Z is a vector, gives the covariance matrix of Z (remember by assumption
#' Z has mean 0 and variance 1).  The (i,j) element of the matrix should be the (i-1)(i-2)/2+j element
#' of the vector.
#' @param cov_W Only used if W is a vector, gives the covariance matrix of W (remember by assumption
#' W has mean 0 and variance 1).  The (i,j) element of the matrix should be the (i-1)(i-2)/2+j element
#' of the vector.
#' @param prob_G Probability that each allele is equal to 1.  Since each SNP has
#' two alleles, the expectation of G is 2*prob_G.
#'
#' @keywords simulation
#' @export
#' @examples 
#' library(mvtnorm)
#' rho_list <- rep(0.3, 6)
#' beta_list <- runif(6)
#' prob_G <- runif(1, min=0.05, max=0.95)
#' GE_bias_results <- GE_bias_normal_squaredmis(beta_list, mu_vec, rho_list)
#' GE_nleqslv(GE_bias_results$beta_list, GE_bias_results$mu_vec, GE_bias_results$cov_vec,
#' 		GE_bias_results$MU_ZZ, GE_bias_results$MU_ZM, GE_bias_results$MU_ZW,
#' 		GE_bias_results$MU_WM, GE_bias_results$MU_WW, GE_bias_results$HOM_vec)
#' GE_scoreeq_sim(beta_list=beta_list, prob_G, rho_list=rho_list)

GE_scoreeq_sim <- function(num_sims=5000, num_sub=2000, beta_list, prob_G, rho_list, cov_Z=NULL, cov_W=NULL)
{
	# Need survival function
	surv <- function(x) {1-pnorm(x)}
  	
  	# Fill in our covariances.
  	rho_GE <- rho_list[[1]]; rho_GZ <- rho_list[[2]]; rho_EZ <- rho_list[[3]]
  	rho_GW <- rho_list[[4]]; rho_EW <- rho_list[[5]]; rho_ZW <- rho_list[[6]]
  	
  	# Quantities necessary for calculating higher order moments
  	w <- qnorm(1-prob_G)					
    r_GE <- rho_GE / (2*dnorm(w))	
    r_GZ <- rho_GZ / (2*dnorm(w))
    r_GW <- rho_GW / (2*dnorm(w))
    num_Z <- length(beta_list[[5]])
  	num_W <- length(beta_list[[6]])
   
   	# Get the total covariance matrix (also some basic validity checks)
	translated_inputs <- GE_translate_inputs(beta_list=beta_list, rho_list=rho_list, 
									prob_G=prob_G, cov_Z=cov_Z, cov_W=cov_W)
	sig_mat <- translated_inputs$sig_mat_total
	sig_mat_ZZ <- translated_inputs$sig_mat_ZZ
	sig_mat_WW <- translated_inputs$sig_mat_WW


	results <- matrix(data=NA, nrow=num_sims, ncol=(4+num_Z+num_W))
	for(i in 1:num_sims)
	{
		# Sim covariates
		sim_data <- mvtnorm::rmvnorm(n=num_sub, mean=c(rep(0,3+num_Z+num_W)), sigma=sig_mat)		
		snp1 <- as.numeric(sim_data[,1]>w)
		snp2 <- as.numeric(sim_data[,2]>w)
		G <- snp1 + snp2 - 2*prob_G
		E <- sim_data[,3]
		Z <- sim_data[,4:(3+num_Z)]
		W <- sim_data[,(4+num_Z):(3+num_Z+num_W)]

		# Sim outcome
		d_right <- cbind(1, G, E^2, G*E^2, Z, W^2)
		d_wrong <- cbind(1, G, E, G*E, Z, W)
		Y <- d_right %*% unlist(beta_list) + rnorm(num_sub)
		
		# Solve for beta_hat
		b_hat <- solve(t(d_wrong) %*% d_wrong) %*% t(d_wrong) %*% Y
		results[i,] <- b_hat
		
		# Checkpoint
		if (i%%1000 == 0) {cat(i, "done\n")}
	}
	colnames(results) <- c('alpha_0', 'alpha_G', 'alpha_E', 'alpha_I', rep('ALPHA_Z',num_Z), rep('ALPHA_W',num_W))
	sim_alpha <- apply(results, 2, mean)
	
	return(sim_alpha)
}

